namespace Avalonia.Input;

/// <summary>
/// Provides basic properties for the input pointer associated with a single mouse, pen/stylus, or touch contact.
/// </summary>
public record struct PointerPoint
{
	/// <summary>
	/// Gets specific pointer generated by input device.
	/// </summary>
	public IPointer Pointer { get; }

	/// <summary>
	/// Gets extended information about the input pointer.
	/// </summary>
	public PointerPointProperties Properties { get; }

	/// <summary>
	/// Gets the location of the pointer input in client coordinates.
	/// </summary>
	public Point Position { get; }

	public PointerPoint(IPointer pointer, Point position, PointerPointProperties properties)
	{
		Pointer = pointer;
		Position = position;
		Properties = properties;
	}
}
