using System;
using System.Collections.Generic;
using Avalonia.Input.Raw;
using Avalonia.Interactivity;
using Avalonia.Metadata;
using Avalonia.Rendering;

namespace Avalonia.Input;

public class PointerEventArgs : RoutedEventArgs, IKeyModifiersEventArgs
{
	private readonly IPresentationSource? _eventPresentationSource;

	private readonly Point _presentationSourcePosition;

	private readonly PointerPointProperties _properties;

	private readonly Lazy<IReadOnlyList<RawPointerPoint>?>? _previousPoints;

	/// <summary>
	/// Gets specific pointer generated by input device.
	/// </summary>
	public IPointer Pointer { get; }

	/// <summary>
	/// Gets the time when the input occurred.
	/// </summary>
	public ulong Timestamp { get; }

	/// <summary>
	/// An opaque platform-specific cookie associated with this event.
	/// Used by backends to pass platform data through the input pipeline.
	/// </summary>
	[PrivateApi]
	public object? PlatformInputEventCookie { get; }

	internal bool IsGestureRecognitionSkipped
	{
		get
		{
			return (Pointer as Pointer)?.IsGestureRecognitionSkipped ?? false;
		}
		private set
		{
			if (Pointer is Pointer pointer)
			{
				pointer.IsGestureRecognitionSkipped = true;
			}
		}
	}

	/// <summary>
	/// Gets a value that indicates which key modifiers were active at the time that the pointer event was initiated.
	/// </summary>
	public KeyModifiers KeyModifiers { get; }

	/// <summary>
	/// Gets the state the pointer device had when this event occurred.
	/// </summary>
	public PointerPointProperties Properties => _properties;

	public PointerEventArgs(RoutedEvent? routedEvent, object? source, IPointer pointer, Visual? rootVisual, Point rootVisualPosition, ulong timestamp, PointerPointProperties properties, KeyModifiers modifiers)
		: base(routedEvent)
	{
		base.Source = source;
		_eventPresentationSource = rootVisual?.PresentationSource;
		_presentationSourcePosition = rootVisualPosition;
		_properties = properties;
		Pointer = pointer;
		Timestamp = timestamp;
		KeyModifiers = modifiers;
	}

	[PrivateApi]
	public PointerEventArgs(RoutedEvent? routedEvent, object? source, IPointer pointer, Visual? rootVisual, Point rootVisualPosition, ulong timestamp, PointerPointProperties properties, KeyModifiers modifiers, Lazy<IReadOnlyList<RawPointerPoint>?>? previousPoints, object? platformInputEventCookie = null)
		: this(routedEvent, source, pointer, rootVisual, rootVisualPosition, timestamp, properties, modifiers)
	{
		_previousPoints = previousPoints;
		PlatformInputEventCookie = platformInputEventCookie;
	}

	private Point GetPosition(Point pt, Visual? relativeTo)
	{
		if (relativeTo == null)
		{
			return pt;
		}
		if (_eventPresentationSource == null || relativeTo?.PresentationSource?.RootVisual == null)
		{
			return default(Point);
		}
		if (relativeTo.PresentationSource != _eventPresentationSource)
		{
			PixelPoint? pixelPoint = _eventPresentationSource.PointToScreen(pt);
			if (pixelPoint.HasValue)
			{
				PixelPoint valueOrDefault = pixelPoint.GetValueOrDefault();
				Point? point = relativeTo.PresentationSource.PointToClient(valueOrDefault);
				if (point.HasValue)
				{
					Point valueOrDefault2 = point.GetValueOrDefault();
					pt = valueOrDefault2;
					goto IL_008b;
				}
			}
			return default(Point);
		}
		goto IL_008b;
		IL_008b:
		return relativeTo.PresentationSource.RootVisual.TranslatePoint(pt, relativeTo).GetValueOrDefault();
	}

	/// <summary>
	/// Gets the pointer position relative to a control.
	/// </summary>
	/// <param name="relativeTo">The visual whose coordinate system to use. Pass null for toplevel coordinate system</param>
	/// <returns>The pointer position in the control's coordinates.</returns>
	public Point GetPosition(Visual? relativeTo)
	{
		return GetPosition(_presentationSourcePosition, relativeTo);
	}

	/// <summary>
	/// Returns the PointerPoint associated with the current event
	/// </summary>
	/// <param name="relativeTo">The visual whose coordinate system to use. Pass null for toplevel coordinate system</param>
	/// <returns></returns>
	public PointerPoint GetCurrentPoint(Visual? relativeTo)
	{
		return new PointerPoint(Pointer, GetPosition(relativeTo), _properties);
	}

	/// <summary>
	/// Returns the PointerPoint associated with the current event
	/// </summary>
	/// <param name="relativeTo">The visual which coordinate system to use. Pass null for toplevel coordinate system</param>
	/// <returns></returns>
	public IReadOnlyList<PointerPoint> GetIntermediatePoints(Visual? relativeTo)
	{
		IReadOnlyList<RawPointerPoint> readOnlyList = _previousPoints?.Value;
		if (readOnlyList == null || readOnlyList.Count == 0)
		{
			return new PointerPoint[1] { GetCurrentPoint(relativeTo) };
		}
		PointerPoint[] array = new PointerPoint[readOnlyList.Count + 1];
		for (int i = 0; i < readOnlyList.Count; i++)
		{
			RawPointerPoint rawPoint = readOnlyList[i];
			array[i] = new PointerPoint(properties: new PointerPointProperties(_properties, rawPoint), pointer: Pointer, position: GetPosition(rawPoint.Position, relativeTo));
		}
		array[^1] = GetCurrentPoint(relativeTo);
		return array;
	}

	/// <summary>
	/// Prevents this event from being handled by other gesture recognizers in the route
	/// </summary>
	public void PreventGestureRecognition()
	{
		IsGestureRecognitionSkipped = true;
	}
}
